apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-mig-monitor-sa
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-mig-monitor-sa
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aks-mig-monitor-sa
subjects:
- kind: ServiceAccount
  name: aks-mig-monitor-sa
  namespace: <NAMESPACE>
roleRef:
  kind: ClusterRole
  name: aks-mig-monitor-sa
  apiGroup: rbac.authorization.k8s.io